### ISSUE TITLE
Blockquotes/context outside of e-content

### ISSUE THREAD

**Issue by janboddez** [jamesvandyne/tanzawa#104]
More of a question/remark than anything else:

When I load https://jamesvandyne.com/feed/ and subsequently read, e.g., https://jamesvandyne.com/ed9f2982-9adf-47a7-b1e8-5624c498728e in my feed reader, it (obviously) displays the blockquote on top (because it's in the feed item).

But when I parse https://jamesvandyne.com/ as a microformats feed (which I prefer, because then I get all of the additional metadata, like reply-to URLs, etc.), the blockquote goes missing: my reader's mf2 parser ([mf2-php](https://github.com/microformats/php-mf2)), I believe, just drops it (it is not in `e-content`, after all).

In a way, that's fine (I have the link to the original article, after all), but if you were replying to a specific paragraph, for instance, that context would be lost (for mf2 followers).

**Comment by jamesvandyne** [comment]
@janboddez Thanks for the comment. That's a good point - are blockquotes considered part of the content? Logically I have the reply/blockquote separate from the reply content itself. But I suppose block quote should also be considered part of the content...I'll see if I can't rework the template to include the blockquote under e-content.

**Comment by jamesvandyne** [comment]
@janboddez I think I've fixed and deployed the issue, Let me know if all is well. 

Cheers,

James

**Comment by janboddez** [comment]
Yep, looks good!

(Left: RSS; right: HTML/microformats)
![afbeelding](https://user-images.githubusercontent.com/8428432/133742946-9d399548-fb07-4c89-a922-e2e728728ffb.png)
