### ISSUE TITLE
Checkins not parsed as such?

### ISSUE THREAD

**Issue by janboddez** [jamesvandyne/tanzawa#106]
Disclaimer: not too big a fan of checkins. That said, I noticed, e.g., X-Ray (which I use for my home-grown feed reader, too, and relies on mf2-php) doesn't seem to pick up https://xray.p3k.app/parse?url=https%3A%2F%2Fjamesvandyne.com%2F0bb1651e-c6fc-4e41-8c6b-081b7fb79626&pretty=true as a checkin, while, e.g., https://xray.p3k.app/parse?url=https%3A%2F%2Fdavid.shanske.com%2F2021%2F08%2F22%2F5128%2F&pretty=true works fine.

Thinking it's a missing `u-checkin` on (e.g.) the Swarm/Foursquare link. (Guessing you'd also want to add this to checkins on the homepage.)

Wondering if with it, it'll also pick up the coordinates.

**Comment by jamesvandyne** [comment]
@janboddez Thanks for the bug report! I've added the `u-checkin` tag, so everything should be working fine. I have the p-location attribute for the post on the detail page (it's down near the map), but I've now also included it in the u-checkin card.

I hear you with the checkins. I didn't see the point really until I could backfeed them into my blog (with photos) as it allows me to create [collections](https://jamesvandyne.com/trips/6644541e-b289-40a5-9df4-45a200fba42f) as [trips](https://jamesvandyne.com/trips/).

X-Ray seems to be picking up the fixes.

<img width="928" alt="image" src="https://user-images.githubusercontent.com/154726/133867003-f7ad534b-42f2-4504-a73f-95378f4f888c.png">
