### ISSUE TITLE
IndieAuth HTTP error 403

### ISSUE THREAD

**Issue by rmdes** [jamesvandyne/tanzawa#179]
Hi James, 

I'm still configuring it but as a new user I want to understand what I need to do to fix all these problems and document it, so that next users don't have to try it blindly to make it work. 

I'm testing indieAuth, Indiewebify.me and login to the indieweb.org wiki with my tanzawa. 

for IndieAuth I'm getting this : 
![image](https://user-images.githubusercontent.com/12155003/153755202-4a55001e-a990-4756-8812-72466a3cfc3b.png)

`{
    "\n<!DOCTYPE_html>\n<html_lang": "\"en\">\n<head>\n  <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\n  <meta name=\"robots\" content=\"NONE,NOARCHIVE\">\n  <title>403 Forbidden</title>\n  <style type=\"text/css\">\n    html * { padding:0; margin:0; }\n    body * { padding:10px 20px; }\n    body * * { padding:0; }\n    body { font:small sans-serif; background:#eee; color:#000; }\n    body>div { border-bottom:1px solid #ddd; }\n    h1 { font-weight:normal; margin-bottom:.4em; }\n    h1 span { font-size:60%; color:#666; font-weight:normal; }\n    #info { background:#f6f6f6; }\n    #info ul { margin: 0.5em 4em; }\n    #info p, #summary p { padding-top:10px; }\n    #summary { background: #ffc; }\n    #explanation { background:#eee; border-bottom: 0px none; }\n  </style>\n</head>\n<body>\n<div id=\"summary\">\n  <h1>Forbidden <span>(403)</span></h1>\n  <p>CSRF verification failed. Request aborted.</p>\n\n\n  <p>You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.</p>\n  <p>If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for \u201csame-origin\u201d requests.</p>\n\n</div>\n\n<div id=\"info\">\n  <h2>Help</h2>\n    \n    <p>Reason given for failure:</p>\n    <pre>\n    CSRF cookie not set.\n    </pre>\n    \n\n  <p>In general, this can occur when there is a genuine Cross Site Request Forgery, or when\n  <a\n  href=\"https://docs.djangoproject.com/en/3.2/ref/csrf/\">Django\u2019s\n  CSRF mechanism</a> has not been used correctly.  For POST forms, you need to\n  ensure:</p>\n\n  <ul>\n    <li>Your browser is accepting cookies.</li>\n\n    <li>The view function passes a <code>request</code> to the template\u2019s <a\n    href=\"https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render\"><code>render</code></a>\n    method.</li>\n\n    <li>In the template, there is a <code>{% csrf_token\n    %}</code> template tag inside each POST form that\n    targets an internal URL.</li>\n\n    <li>If you are not using <code>CsrfViewMiddleware</code>, then you must use\n    <code>csrf_protect</code> on any views that use the <code>csrf_token</code>\n    template tag, as well as those that accept the POST data.</li>\n\n    <li>The form has a valid CSRF token. After logging in in another browser\n    tab or hitting the back button after a login, you may need to reload the\n    page with the form, because the token is rotated after a login.</li>\n  </ul>\n\n  <p>You\u2019re seeing the help section of this page because you have <code>DEBUG =\n  True</code> in your Django settings file. Change that to <code>False</code>,\n  and only the initial error message will be displayed.  </p>\n\n  <p>You can customize this page using the CSRF_FAILURE_VIEW setting.</p>\n</div>\n\n</body>\n</html>\n"
}`

**Comment by jamesvandyne** [comment]
Hi Ricardo!

Thanks for opening and reporting all the various IndieAuth related issues.

Yes - I've been running into this personally, too. Me attempting to do the finally create an account on indieweb.org is what surfaced #160. My plan is to rewrite the IndieAuth views using [indieweb-utils](https://github.com/capjamesg/indieweb-utils/) once there's a new release, as we added some IndieAuth helpers to it. Doing the rewrite should fix  #160 , #179, #180, and #182.

**Comment by jamesvandyne** [comment]
@rmdes I've just pushed a fix for this in #188  and confirmed I was able to login to IndieWeb.org. Please try again and check if this solves your issue.

**Comment by rmdes** [comment]
IndieAuth login to Indieweb.org is working ! https://indieweb.org/User:Blog.rmendes.net_author_rmdes

**Comment by rmdes** [comment]
Login is also working smoothly with https://indieauth.com
![image](https://user-images.githubusercontent.com/12155003/154655820-83d8d5af-bdee-4128-a09c-87b7352cc7ec.png)

**Comment by rmdes** [comment]
https://indielogin.com/ also works perfectly !

**Comment by jamesvandyne** [comment]
@rmdes Oops. Thanks for checking all of this. I've fixed the issue with Quill, so you should be able to login to any service using IndieAuth now...hopefully :)

**Comment by rmdes** [comment]
So I pushed the latest code to my docker image, did a migration just to be sure and tested Quill : 
![image](https://user-images.githubusercontent.com/12155003/154799626-db5adccf-34f5-4105-9761-8b3624a659c2.png)
I got a bit more verbose error at micropublish : 
![image](https://user-images.githubusercontent.com/12155003/154799650-b25f50f2-0ecf-4934-ab20-cc9ce63f2cc9.png)
or https://unicyclic.com
![image](https://user-images.githubusercontent.com/12155003/154799660-00f2e907-26e5-40bb-bc96-f1e383a78a2c.png)

**Comment by rmdes** [comment]
In my quest to test different tools to use indieAuth, I tested with http://cweiske.de/shpub.htm
![image](https://user-images.githubusercontent.com/12155003/154800511-332fc7d0-1b84-4caf-843a-eb82adb87e6d.png)

it seems the redirect URI is wrong ?
but I'm not sure if that comes from Tanzawa or shpub :/ ?
![image](https://user-images.githubusercontent.com/12155003/154800559-18b28787-c8dd-477a-8276-902662fd0fae.png)

**Comment by jamesvandyne** [comment]
@rmdes I think you're still running a slightly old version. I merged a new PR yesterday morning which fixed Quil and verified it's working with my site this morning.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/154726/154818995-b2d4889b-a750-4ba6-b8dd-57f9a25eab7e.png">

As per shpub, the redirect uri comes from shpub, as it's what tells Tanzawa where the redirect to. In the Indieauth spec it says this about the redirect_uri parameter:

>If the URL scheme, host or port of the redirect_uri in the request do not match that of the client_id, then the authorization endpoint SHOULD verify that the requested redirect_uri matches one of the [redirect URLs](https://indieauth.spec.indieweb.org/#redirect-url) published by the client, and SHOULD block the request from proceeding if not.

The fix is nothing Tanzawa can do, but rather we need `http://cweiske.de/shpub.htm` to update their html or http configuration to include a [redirect_uri](https://indieauth.spec.indieweb.org/#redirect-url) that matches what they pass, so `http://127.0.0.1:12345/callback`

**Comment by jamesvandyne** [comment]
I just logged in to unicyclic.com without error as well. (I've never heard of it, but it looks pretty neat!)

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/154726/154819400-ee5ca8c1-0a73-49ae-baff-6c0c044f8ea8.png">

**Comment by rmdes** [comment]
Strange because i did a git pull & python migrate, but maybe should have restarted the container?

Will try again & double check!

Super excited that it works!

**Comment by rmdes** [comment]
I Checked, Repo is already up to date.. Maybe i should rebuild the image but that doesn't make sense..it should just run with latest code..

**Comment by jamesvandyne** [comment]
I'm not sure how you've setup the Docker image, but you'll probably need to rebuild the image / restart the container.

**Comment by rmdes** [comment]
In my case, my container is writable
For the previous commit/merge it worked perfectly, but im going to do a rebuild and see how it goes, thanks!

**Comment by rmdes** [comment]
This is what I keep having without the rebuild, 
![image](https://user-images.githubusercontent.com/12155003/154821086-bf267258-408c-4914-9020-5d13d3b84a49.png)

/me building  now..

**Comment by rmdes** [comment]
Not sure what's happening, but my rebuild stays in "migration loop" 
![image](https://user-images.githubusercontent.com/12155003/154833713-91e11824-4bca-4576-971f-0e4642a6688b.png)

**Comment by rmdes** [comment]
It's really strange... 
when I put my container in recovery mode and start the server all seems to be fine, but when the container restart and should boot the server on it's own, i'm stuck in migration loop..
![image](https://user-images.githubusercontent.com/12155003/154836698-642697d9-04f4-4e29-8f48-44e69400cee4.png)

**Comment by jamesvandyne** [comment]
As IndieAuth is working, I'm going to close this issue. If you run into new issues, let me know!
