### ISSUE TITLE
Features suggestion : support Open Graph

### ISSUE THREAD

**Issue by rmdes** [jamesvandyne/tanzawa#191]
When you share your blog or any link from it to any kind of social network, silo's or fediverse, the way the link display could get some love, open graph would be a neat way to improve this : 
screenshot from a Known powered blog :
![image](https://user-images.githubusercontent.com/12155003/154918091-54d0afd5-98e9-46e1-83b6-4c5e374b4e2c.png)
screenshot from tanzawa when tested with open graph check : 
![image](https://user-images.githubusercontent.com/12155003/154917976-07213ff2-48b9-4770-b34b-37664ce26746.png)

https://www.opengraph.xyz/url/https%3A%2F%2Fblog.rmendes.net/
![image](https://user-images.githubusercontent.com/12155003/154919331-510dcbf7-b869-49d0-b088-aff5850abdf3.png)

Maybe Django Meta could help here ? https://django-meta.readthedocs.io/en/latest/installation.html

**Comment by jamesvandyne** [comment]
Yes it does. Thanks for opening the issue, I always forget to get around to this.

**Comment by jamesvandyne** [comment]
@rmdes I've merged support for open graph data. There might be some room for improvement, but it's a start. You'll want to set the `DOMAIN_NAME` environment variable in your `.env` file.  I've also added the django-meta package as a dependency, so you'll want to install requirements again as well.

```
DOMAIN_NAME=blog.rmendes.net
```
