### ISSUE TITLE
Offer a hook for the RSS/Atom feed

### ISSUE THREAD

**Issue by MaybeThisIsRu** [jamesvandyne/tanzawa#203]
Not sure if the feed content is generated separately, but on the lines of https://rusingh.com/adding-a-comment-via-email-convenience-link/, I'd like to add a "Reply via email" to all posts.

This could be implemented several ways but I think a hook offers the most simplicity and flexibility.

**Comment by jamesvandyne** [comment]
Oh, I like this idea. The encoded content for feeds is generated in this function. [get_encoded_content](https://github.com/jamesvandyne/tanzawa/blob/main/apps/domain/feeds/queries.py#L5).

Maybe a small plugin hook + a plugin to handle the email functionality would be the best way to go about implementing this... as I imagine one would want to control the:

* Destination email address / to name
* Link text
* Email subject?

**Comment by jamesvandyne** [comment]
@MaybeThisIsRu I've added a hook / initial version of the plugin (no customization) in #205. If you're curious how it all works, step through each commit :)

**Comment by MaybeThisIsRu** [comment]
I think you can close this now. :)

Also would be glad to see these links on your site (if you choose to add them!). That's originally what motivated me to open the issue. I think it was your chai tea latte post that got me a little bit hassled that I couldn't easily start a conversation. ;)

**Comment by jamesvandyne** [comment]
> Also would be glad to see these links on your site (if you choose to add them!). 

Yes! Right now I've got a hack in place on my site, with a generic link at the bottom of each page. But I now that I've got a plugin, it wouldn't be too difficult to add hooks for the bottom of the posts etc..
