### ISSUE TITLE
Comment by email plugin issues

### ISSUE THREAD

**Issue by MaybeThisIsRu** [jamesvandyne/tanzawa#219]
It seems to be...broken?

Included in the title + no newline at the end:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/3974019/165680848-55c542e0-6ec2-4781-9f4f-56c88dbb097f.png">

No newline at the end:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/3974019/165680879-70a9cf6b-0b69-4770-b54f-42b5a359b629.png">

**Comment by janboddez** [comment]
Just wanted to remark the same. In the RSS feed, there's no space/newline before the "Comment by email" link. Which is probably also why it ends up in the (autogenerated by Miniflux?) title.

**Comment by janboddez** [comment]
(Minor remark: the items on the homepage/h-feed don't have this comment by email link in their `e-content`. Which is probably by choice, but I just thought I'd mention it.)

**Comment by jamesvandyne** [comment]
For checkins to appear with photos in micro.blog, those post must not have a title set. And RSS readers might use the first line of the body for the title. And as it's appearing on the same line (seemingly when there's a Location), the link is showing up in the title. I'll get it sorted :) Thanks for the bug report's!
