### ISSUE TITLE
Post Visibility

### ISSUE THREAD

**Issue by jamesvandyne** [jamesvandyne/tanzawa#35]
Add support for visibility controls to posts.

- Public
- Unlisted
- Only me (logged in users)

Unlisted and private posts should not appear in feeds / streams / sitemaps unless the user is logged in. Should indicate that it's not visible somehow on the page.

**Comment by hirusi** [comment]
Might these be of any help?

- https://jlelse.blog/micro/2021/07/2021-07-14-snooq
- https://goblog.app/updates/2021/07/updates-2

I think you [blogged recently](https://jamesvandyne.com/20f1f67a-a151-4e3e-8570-fb5c25cce537) about wanting to post replies and such without crowding the main feed.

**Comment by jamesvandyne** [comment]
@hirusi Yeah, Jan actually was inspired by my Tanzawa posts to build that out, he just beat me. I've got it working a draft PR. Just need to get the RSS feeds filtering (couple lines) and to confirm the forms are working and it's good to go. If I can get a solid hour tomorrow it'll be metered. :)

**Comment by hirusi** [comment]
Oh, that makes sense. And no rush, I'm not even using Tanzawa yet. Just kinda trying to open feature requests or help you out in any way I can for things that I "wish" for. Who knows if and when I will switch.
