### ISSUE TITLE
Mobile posting + Markdown support

### ISSUE THREAD

**Issue by pimoore** [jamesvandyne/tanzawa#75]
Hi James,

Is there currently — or going to be — a mobile posting workflow?  Perhaps related to that, does Tanzawa have the ability to sync with GitHub and build posts from Markdown?

Cheers,
-Pete

**Comment by jamesvandyne** [comment]
Hi Pete,

Thanks for the questions. Tanzawa supports micropub and indieauth, so you should be able to post with any client that supports them. It also has a responsive interface so you can post from your web-browser on mobile as well.

Regarding syncing with GitHub/Markdown support, no, it does not. Tanzawa stores all posts in a SQLite database. You _may_  be able to post Markdown using the a Micropub client, but as Tanzawa doesn't do anything special for Markdown, I'm not sure how they would appear on the site.

James

**Comment by pimoore** [comment]
@jamesvandyne Just to clarify, when you say it doesn’t do anything special for Markdown did you mean it doesn’t process Markdown directly?  I don’t know how micropub clients work behind the scenes as to whether they convert the Markdown to HTML before sending through the API, or just send the raw Markdown as is.

**Comment by jamesvandyne** [comment]
@pimoore Correct – all authoring inside of Tanzawa is done via the WYSIWYG editor ( Trix ), it doesn't process Markdown. My understanding is that Micropub clients _should_ be converting the Markdown to HTML before sending the request to the API.

**Comment by rmdes** [comment]
Gonna test this out with the Indigenous android app & report back here.

**Comment by jamesvandyne** [comment]
Closing this with a small note that there is a mobile-posting interface now, at least for statuses.
