### ISSUE TITLE
Git + Docker error

### ISSUE THREAD

**Issue by pimoore** [jamesvandyne/tanzawa#76]
Hi James,

Encountering a couple of errors from the docker prep steps:

1. When trying to clone from the git instructions, I receive the following message:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
**I got around this by using the https link instead**

2. I keep getting the following error at the docker build stage:
"docker image build" requires exactly 1 argument.
See 'docker image build --help'.
Usage:  docker image build [OPTIONS] PATH | URL | -
Build an image from a Dockerfile

Any idea why it’s not working?

Cheers,
-Pete

**Comment by jamesvandyne** [comment]
@pimoore 

1. Thanks. I think if you have a public key registered with GitHub, it  _should_ work using ssh. I'm glad you were able to work around using the ssh key.
2. I forgot a character in the command. The appropriate command is `docker image build . -t tanzawa` ( The `.` after build tells Docker to use the current directory).

Let me know if this works.

James

**Comment by leonstafford** [comment]
Tacking on first test notes here (maybe enable GitHub Discussions?)

Was able to follow the steps in readme (with above mentioned adjustment of Docker build/tag cmd).

I wouldn't assume Python to be on the host OS, though, so maybe could use alternative for the secret key gen?

Opening page could use some text.

<img width="1438" alt="Screen Shot 2021-06-22 at 12 37 39 pm" src="https://user-images.githubusercontent.com/2066833/122856851-b5762880-d356-11eb-9f8f-ad8e8267216a.png">

I reread instructions and checked login - works fine.

**Comment by jamesvandyne** [comment]
@leonstafford 

Awesome. Glad to hear you got it running. I've opened discussions (and started one, too) about improving the first run in Tanzawa.   #78 

Any ideas for alternatives for the secret key gen? When I was researching how to do it, I ran into issues where it wouldn't run on macOS (BSD utils) or commands are Linux only (gnu utils) - Python seemed like a good compromise as it's standard on most platforms these days? Maybe this should move to a discussion...

Fixed the README in #79.

**Comment by pimoore** [comment]
@jamesvandyne @leonstafford 

I was able to get this running on a VPS, but after logging in I’m receiving the following error:
![B1958C06-A19E-463D-8D67-AE6F9D3225CB](https://user-images.githubusercontent.com/5413470/123002158-9770ee00-d37f-11eb-9fd6-9d6d0ed216eb.jpeg)
I use an iPad and have tried accessing the site in both Safari and Firefox Focus with no luck.  Any idea how to get around this?

**Comment by jamesvandyne** [comment]
@pimoore 

Which page did you receive this error on? What did you do to get this error? I'm wondering if the last bullet point may be what caused the issue?

Also, if you're running it on a server, change your DEBUG in your .env file to False (and restart Tanzawa for it to take effect), you don't want to be leaking your secret keys and so forth any time there's an error.

**Comment by pimoore** [comment]
This came up immediately following the login page after inputting my username and password, so I never got what the last bullet states about reloading the form page.  I’ll change the DEBUG option right now though.

**Comment by jamesvandyne** [comment]
Hrmm. Try reloading the login page and logging in again. It sounds like maybe something got cached?

**Comment by pimoore** [comment]
I think I might be in over my head with this. 😂 I deleted and re-created the VPS and went through all the same steps, but now at the login page it has no styling applied and my username and password don’t get accepted at all.  Obviously I’ve done something different than the initial time, but I have no idea what that would be.

**Comment by hirusi** [comment]
For what it's worth, I made a run locally and everything was perfect on first run. Linux _and_ a Django customer. :)

**Comment by rmdes** [comment]
Can the docker image be built with only the requirements.txt (not the dev one?)
- getting issue with it with black 22.1.0 depends on typing-extensions>=3.10.0.0; python_version < "3.10"
    The user requested (constraint) typing-extensions==3.7.4.3
