### ISSUE TITLE
Bookmark RSS feed item broken?

### ISSUE THREAD

**Issue by hirusi** [jamesvandyne/tanzawa#87]
![image](https://user-images.githubusercontent.com/3974019/124496615-475e4680-ddd7-11eb-974b-4fb8a72df1b4.png)

This is what I got today. Had happened a few days ago too. The body text in front of `Bookmark: ` appears to be broken.

**Comment by jamesvandyne** [comment]
Thanks for the bug report! I've fixed it and a couple other minor issues :)

**Comment by hirusi** [comment]
No problem, glad to help! :)
